dist: xenial

notifications:
  email: false

# code language
language: python
python:
  - "3.8"

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script:
  - python main_rulebased.py --novid --test
  - python main_rl.py --novid --test
  - python main_multi.py --novid --test